export const GET_TWEETS_USERNAME_REQUEST = 'GET_TWEETS_USERNAME_REQUEST';
export const GET_TWEETS_KEYWORD_REQUEST = 'GET_TWEETS_KEYWORD_REQUEST';
export const GET_TWEETS_SUCCESS = 'GET_TWEETS_SUCCESS';
export const GET_TWEETS_FAIL = 'GET_TWEETS_FAIL';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const CHANGE_SEARCH_CRITERIA = 'CHANGE_SEARCH_CRITERIA';
export const CLEAR_TWEET_LIST = 'CLEAR_TWEET_LIST';