export const GET_TWEETS_REQUEST = 'GET_TWEETS_REQUEST';
export const GET_TWEETS_SUCCESS = 'GET_TWEETS_SUCCESS';
export const GET_TWEETS_FAIL = 'GET_TWEETS_FAIL';
export const GET_TWEET_USERS_SUCCESS = 'GET_TWEET_USERS_SUCCESS';
//export const GET_TWEET_USERS_FAIL = 'GET_TWEET_USERS_FAIL';
export const CLEAR_TWEET_LIST = 'CLEAR_TWEET_LIST';